// Code generated by entc, DO NOT EDIT.

package ent

import (
	"ent-naming-conflict/ent/message"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
}
